name: Merge to Main
run-name: Merging ${{ github.ref_name }} into Main
on:
    pull_request:
      types: [closed]
      branches: [main]
jobs:
  Create-Service-Container-Image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ronaldddd/test-repo:latest
